-- 코드를 입력하세요


SELECT MEMBER_NAME,	REVIEW_TEXT,	DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") as REVIEW_DATE

FROM

(SELECT *
FROM REST_REVIEW) AS REVIEW

JOIN

(SELECT *
FROM MEMBER_PROFILE
WHERE MEMBER_ID = (SELECT MEMBER_ID
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(*) DESC
                    LIMIT 1)) AS MEMBER

ON MEMBER.MEMBER_ID = REVIEW.MEMBER_ID

order by  REVIEW_DATE, REVIEW_TEXT