-- 코드를 입력하세요
SELECT INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES ,ADDRESS, round(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS INFO
JOIN REST_REVIEW AS REVIEW ON INFO.REST_ID = REVIEW.REST_ID
where left(ADDRESS,2) = "서울"
GROUP BY INFO.REST_ID
order by SCORE desc, FAVORITES desc