-- 코드를 작성해주세요
SELECT ID,	EMAIL,	FIRST_NAME,	LAST_NAME
FROM DEVELOPERS D
WHERE EXISTS (SELECT *
      FROM SKILLCODES S
      WHERE (NAME = "Python" AND D.SKILL_CODE & S.CODE = S.CODE)
       OR (NAME = "C#" AND D.SKILL_CODE & S.CODE = S.CODE)
      )
ORDER BY ID